entrada=input()
print("É alnum: ",entrada.isalnum())
print("É alpha: ",entrada.isalpha())
print("É  ASCII: ", entrada.isascii())
print("É decimal: ",entrada.isdecimal())
print("É digit: ",entrada.isdigit())
print("É dentifier: ",entrada.isidentifier())
print("É lower: ",entrada.islower())
print("É numeric: ",entrada.isnumeric())
print("É printable: ",entrada.isprintable())
print("É space: ",entrada.isspace())
print("É title: ",entrada.istitle())
print("É upper: ",entrada.isupper())
print("Tipo da entrada: ",type(entrada))
